# Generated by Django 3.2.9 on 2021-12-09 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_author_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dateModified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dateModified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='totalComments',
            new_name='total_comments',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='totalLikes',
            new_name='total_likes',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='totalLikes',
        ),
        migrations.AlterField(
            model_name='postlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='database.post'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
