# Generated by Django 3.2.9 on 2021-12-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_author_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_modified',
        ),
    ]
